### ISSUE TITLE
ImportError: cannot import name api

### ISSUE THREAD

**Issue by SHABINTHEGREAT** [charliewolf/pynder#117]
**What is the solution to this Error while importing pynder?
ImportError: cannot import name api**

```
>>> import pynder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pynder/__init__.py", line 1, in <module>
    from .session import Session  # NOQA
  File "/Library/Python/2.7/site-packages/pynder/session.py", line 3, in <module>
    from . import api
ImportError: cannot import name api
```

**Comment by sfgasdfsafggfgg** [comment]
try importing it in python 3, maybe Pynder doesn't work with python 2.7

**Comment by charliewolf** [comment]
Try latest master. should be resolved.
